---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

Load the necessary libraries to be used in the code
```{r Ophalen bibliotheken, warning=FALSE, message=FALSE, paged.print=FALSE}
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl)               # Voor het inlezen van data uit Excel
library(lubridate)            # Voor het interpreteren van datums, tijden en periodes 
library(RSQLite)              # voor de ondersteuning van SQL in R
```

Haal data op uit Excel en plaats die in een SQLite database
```{r Inladen data in SQLite database, message=FALSE, warning=FALSE}
database <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(database, name="buurt",     df = read_excel('~/R/Datasets/Van der Binckes Sharing/Buurten.xlsx'))
copy_to(database, name="CAO",       df = read_excel('~/R/Datasets/Van der Binckes Sharing/CAO.xlsx'))
copy_to(database, name="fiets",     df = read_excel('~/R/Datasets/Van der Binckes Sharing/Fietsen.xlsx'))
copy_to(database, name="fietstype", df = read_excel('~/R/Datasets/Van der Binckes Sharing/FietsTypes.xlsx'))
copy_to(database, name="klant",     df = read_excel('~/R/Datasets/Van der Binckes Sharing/Klanten.xlsx'))
copy_to(database, name="locatie",   df = read_excel('~/R/Datasets/Van der Binckes Sharing/Locaties.xlsx'))
copy_to(database, name="medewerker",df = read_excel('~/R/Datasets/Van der Binckes Sharing/Medewerkers.xlsx'))
copy_to(database, name="onderhoud", df = read_excel('~/R/Datasets/Van der Binckes Sharing/OnderhoudsData.xlsx'))
copy_to(database, name="rooster",   df = read_excel('~/R/Datasets/Van der Binckes Sharing/Rooster.xlsx'))
copy_to(database, name="schade",    df = read_excel('~/R/Datasets/Van der Binckes Sharing/Schades.xlsx'))
copy_to(database, name="sharing",   df = read_excel('~/R/Datasets/Van der Binckes Sharing/SharingData.xlsx'))
copy_to(database, name="stadsdeel", df = read_excel('~/R/Datasets/Van der Binckes Sharing/Stadsdelen.xlsx'))
copy_to(database, name="weer",      df = read_excel('~/R/Datasets/Van der Binckes Sharing/Weerdata.xlsx'))
copy_to(database, name="wijk",      df = read_excel('~/R/Datasets/Van der Binckes Sharing/Wijken.xlsx'))
```

Maak een overzicht van de sharing
```{sql connection=database}
select Land, count(*)
from Klant
left outer join sharing
  on sharing.KlantID = Klant.ID
where sharing.KlantID IS NULL
group by Land

/*
Land            count(*)
-------------- ---------
Belgium	            16			
Germany	           163			
Netherlands	       216			
United Kingdom	   105	
*/
```


## Voeg hier je eigen chunks toe



```


